[package]
name = "cuts"
version = "0.1.1"
edition = "2021"
description = "Constant Uniformity Time Scale"
license = "Apache 2.0 or MIT"
repository = "https://github.com/diabloxenon/cuts"
exclude = ["target/*", "bak/*"]

[dependencies]
rand = "0.8.5"
